task :default => :doc

desc "Ejecutar las espectativas de la clase Nutri"
task :spec do
  sh "rspec -I. spec/nutri_spec.rb"
end

desc "Ejecutar con documentacion"
task :doc do
  sh "rspec -I. spec/nutri_spec.rb --format documentation"
end